### ISSUE TITLE
Inline workers break SW generation because they call closeBundle early

### ISSUE THREAD

**Issue by NotWoods** [antfu/vite-plugin-pwa#46] opened 2021-04-12 00:26 UTC
When generating an inline web worker, Vite passes all its plugins to Rollup to create a bundle for the worker. Unfortunately that inner Rollup job [calls bundle.close and triggers closeBundle](https://github.com/vitejs/vite/blob/main/packages/vite/src/node/plugins/worker.ts#L62) before any files are in the output folder. As a result, workbox-build throws an error because it can't find anything.

**Comment by userquin** [comment] 2021-04-12 00:42
@NotWoods can you include errors and vite and npm/pnpm/yarn versions? It seems to be a problem with `vite` itself.

**Comment by userquin** [comment] 2021-04-12 00:45
@NotWoods Can you provide a repro?

**Comment by userquin** [comment] 2021-04-12 01:32
The line linked is a bug that is being solved in vite,  the problem is that these line doesn't await promise returned and then is closed at any time later and in your case breaking the build.

**Comment by userquin** [comment] 2021-04-12 02:02
The line you link on vite should be like this: https://github.com/antfu/vite-plugin-pwa/blob/master/src/modules.ts#L52

In fact in your vite pr you have the same error, add await when closing the bundle...

**Comment by userquin** [comment] 2021-04-12 23:27
I write you on discord (`ViteLand`) on `plugins` chat: this must be fixed on `vite` side.

@antfu we should review if only including `vite:esbuild`, `vite:resolve` and `vite:terser` instead excluding, we need to do some tests.

**Comment by userquin** [comment] 2021-06-12 01:28
@NotWoods see https://github.com/antfu/vite-plugin-pwa/issues/68#issuecomment-859977520

**Closed** 2021-06-12 07:38 UTC
