### ISSUE TITLE
React-Router Blank Page after Reload after Open (From Browser)

### ISSUE THREAD

**Issue by fadi-george** [antfu/vite-plugin-pwa#230] opened 2022-02-22 03:33 UTC
Hello, I noticed that reloading after opening the installed app leads to a blank page.

Commit: main / 99f204b00b984d26a06c7eb1f1b465077751f151

Steps:
- run examples (react-router)
```
➜  vite-plugin-pwa git:(main) ✗ npm run examples

> vite-plugin-pwa@0.11.13 examples
> esno scripts/run-examples.ts

✔ Select a framework: › react
✔ Select a strategy: › generateSW
✔ Select a behavior: › Prompt for update
✔ Enable periodic SW updates? … no / yes

> example-react-router@0.0.0 start /Documents/Code/vite-plugin-pwa/examples/react-router
> npm run run-build && npm run serve


> example-react-router@0.0.0 run-build
> cross-env DEBUG=vite-plugin-pwa:* BASE_URL=/ SOURCE_MAP=true vite build

vite v2.7.1 building for production...
[plugin:replace] @rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
✓ 38 modules transformed.
dist/index.html                  0.74 KiB
dist/manifest.webmanifest        0.38 KiB
dist/assets/index.6aace04c.js    4.45 KiB / gzip: 1.62 KiB
dist/assets/index.6aace04c.js.map 12.34 KiB
dist/assets/index.894c95d0.css   1.01 KiB / gzip: 0.53 KiB
dist/assets/vendor.e582f5bb.js   143.10 KiB / gzip: 46.80 KiB
dist/assets/vendor.e582f5bb.js.map 349.05 KiB

PWA v0.11.13
mode      generateSW
precache  8 entries (149.38 KiB)
files generated
  dist/sw.js.map
  dist/sw.js
  dist/workbox-5dcc6b36.js.map
  dist/workbox-5dcc6b36.js

> example-react-router@0.0.0 serve
> serve dist

Serving static path: dist
http to https redirection active.
Server running on port 443.
```

- go to localhost
- install app
![Screen Shot 2022-02-21 at 7 24 57 PM](https://user-images.githubusercontent.com/6709400/155057516-b69573e3-a4e6-4727-a145-dfaedff7f9a1.png)

- close app
- go to localhost again
- open app (from the browser)
![Screen Shot 2022-02-21 at 7 26 25 PM](https://user-images.githubusercontent.com/6709400/155057634-6701f438-ca16-458f-83c0-e869edc19e9f.png)

- close the app again
- open the app again (from the browser)

- refresh/reload (e.g. CMD + R)
- see blank page (if not blank, close then reopen again from browser)

<img width="1198" alt="Screen Shot 2022-02-21 at 7 29 01 PM" src="https://user-images.githubusercontent.com/6709400/155057860-b816b6c8-b527-43c0-a2b3-7d82b5be8fc4.png">

**Comment by fadi-george** [comment] 2022-02-22 03:36
Running the app from a location like Applications / Chrome Apps / PWA Router and reloading there doesnt seem to produce blank page

**Comment by userquin** [comment] 2022-02-22 12:11
@fadi-george 

On windows I cannot reproduce it: can you test it with the dev tools opened, maybe there is some error? tested with vue and react router examples

**Comment by fadi-george** [comment] 2022-02-24 21:30
I also tested on Windows and it doesn't seem to have that problem. Also for Mac, even if it appears blank you can still hover/interact with button elements I believe.

**Comment by fadi-george** [comment] 2022-02-25 01:30
<CssBaseline /> (Mui) seems to cause the blank page at least for my app

**Comment by userquin** [comment] 2022-03-09 13:37
@fadi-george  closing this, it seems a problem not related with this repo, feel free to open a new issue...

/cc @antfu can you enable discussions here?

**Closed by userquin** 2022-03-09 13:37 UTC
