### ISSUE TITLE
WorkboxError non-precached-url index.html

### ISSUE THREAD

**Issue by jonian** [antfu/vite-plugin-pwa#120] opened 2021-08-21 14:55 UTC
Hi, thank you for this plugin. 

I'm getting the error below when running the app with `vite preview` and in production. The app source code is available at https://github.com/jonian/awmonitor and the production link is https://awmonitor.netlify.app.

```
WorkboxError.js:28 Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"index.html"}]
    at x.createHandlerBoundToURL (http://localhost:5000/workbox-a59a8da5.js:1:12967)
    at Object.createHandlerBoundToURL (http://localhost:5000/workbox-a59a8da5.js:1:14597)
    at http://localhost:5000/sw.js:1:10085
    at http://localhost:5000/sw.js:1:695
s @ WorkboxError.js:28
createHandlerBoundToURL @ PrecacheController.js:276
(anonymous) @ createHandlerBoundToURL.js:29
(anonymous) @ sw.js:486
(anonymous) @ sw.js:1
```

**Comment by userquin** [comment] 2021-08-21 15:05
@jonian can you try removing `?standalone=true` from the `start_url` with `vite preview`?.

**Comment by userquin** [comment] 2021-08-21 15:18
The problem is that routes are not added to the sw precache, you need to add them manually, I'll push changes to my fork and make a PR to your repo.

You can see this comment https://github.com/antfu/vitesse/issues/159 for an explanation.

**Comment by userquin** [comment] 2021-08-21 15:32
Well, the problem is on your `workbox.globPatterns` entry: you need to include all, it is exclusive, that is, if you include this entry, you MUST add all your patterns, not only assets: in your case, you are not including js and css assets.

Since you are using `vite`, all entries under `assets` directory will be included, you don't need to add them again.

Just remove the `workbox` entry from your configuration:

![imagen](https://user-images.githubusercontent.com/6311119/130326881-095e781c-3331-4be2-9de0-980c8deb1059.png)

![imagen](https://user-images.githubusercontent.com/6311119/130326903-e72b501a-a466-4f08-b06b-bc8bdc331530.png)

You also need to add all red entries shown bellow to make it work offline, it is working, but some images missing:

![imagen](https://user-images.githubusercontent.com/6311119/130326994-5af15250-de97-486a-a4ca-d76a012eb3c5.png)

**Closed** 2021-08-21 15:33 UTC

**Comment by jonian** [comment] 2021-08-21 15:35
Thanks for the quick response and the help @userquin

**Comment by userquin** [comment] 2021-08-21 15:36
@jonian I will add some entry on docs when using `globaPatterns` and some other similar entries from `workbox` and `injectManifest` to avoid this type of problems...

**Comment by jonian** [comment] 2021-08-21 16:01
Thank you again @userquin, that will be really helpful.

**Comment by jonian** [comment] 2021-08-21 16:47
> You also need to add all red entries shown bellow to make it work offline, it is working, but some images missing

@userquin there are no images missing, they are the fonts the app uses from `@iconscout/unicons`. If I remove the font entries from the `workbox` config, the fonts are not available in offline mode. If I use the config below, everything works as expected in offline mode.

```js
workbox: {
  globPatterns: [
    '*/*.*',
    '*.*'
  ]
}
```

Without the `workbox` option in offline mode:

![Screenshot from 2021-08-21 19-41-39](https://user-images.githubusercontent.com/4119508/130329044-118644b1-df75-40a5-a7ad-9d7b66c92de5.png)


With the `workbox` option above in offline mode:

![Screenshot from 2021-08-21 19-38-51](https://user-images.githubusercontent.com/4119508/130329059-880de3ea-899b-4bd0-bef9-1545035e268a.png)

**Comment by userquin** [comment] 2021-08-21 17:42
@jonian read this entry to configure properly your external fonts: https://vite-plugin-pwa.netlify.app/workbox/generate-ws.html#cache-external-resources

Basically you need to add crossorigin and then add runtimeCaching for fonts urls. I suggest you to add also `dns-prefetch` links.

**Comment by userquin** [comment] 2021-08-21 17:48
@jonian I have included a warning on `Static Assets Handling` entry: just go to https://vite-plugin-pwa.netlify.app/guide/static-assets.html and wait for prompt for update and then click reload button.

**Comment by Ehesp** [comment] 2022-07-19 11:55
Sorry to pickup an old thread here, however this is causing some confusion for me.

I'm using Vite to SSR a page, however the `index.html` file gets added to the client bundle even though it's not served by users. My server returns the HTML, however with the index.html file being cached, it's returning the version of my html which is missing things (e.g. I replace `<!-- app-head -->` on the server to add metadata). The SW kicks in and serves the cached file instead of the server.

If I add the html file to the ignore glob, I get the `non-precached-url: non-precached-url` error described here.

**Comment by Charles-1999** [comment] 2022-08-02 12:00
> Sorry to pickup an old thread here, however this is causing some confusion for me.
> 
> I'm using Vite to SSR a page, however the `index.html` file gets added to the client bundle even though it's not served by users. My server returns the HTML, however with the index.html file being cached, it's returning the version of my html which is missing things (e.g. I replace `<!-- app-head -->` on the server to add metadata). The SW kicks in and serves the cached file instead of the server.
> 
> If I add the html file to the ignore glob, I get the `non-precached-url: non-precached-url` error described here.

@userquin I have got a similar problem, how can i exclude the html file.

**Comment by userquin** [comment] 2022-08-02 13:45
@Ehesp you're right, the default value when undefined is configured by the options module with `index.html`, so you need to set it to null.

**Comment by Ehesp** [comment] 2022-08-02 14:23
I made a quick PR to update the type docs: https://github.com/GoogleChrome/workbox/pull/3106

**Comment by jwandekoken** [comment] 2023-02-22 18:02
> I use this config now - not sure if it's fully correct but seems to be working:
> 
> ```js
> {
>   strategies: 'generateSW',
>   workbox: {
>     // Only precache these files - html should be excluded
>     globPatterns: ['**/*.{js,css}'],
> 
>     // Don't fallback on document based (e.g. `/some-page`) requests
>     // Even though this says `null` by default, I had to set this specifically to `null` to make it work
>     navigateFallback: null,
> }
> ```
> 
> This seems to remove the generated config containing the index.html, which is then just handled by the server.

Thanks. I was having the same issue here, this config. helped out.
