### ISSUE TITLE
After packaging, registersw.js is not automatically introduced into index.html

### ISSUE THREAD

**Issue by 1018715564** [antfu/vite-plugin-pwa#74] opened 2021-06-08 09:45 UTC
"vite": "^2.3.5"

```js
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import viteCompression from "vite-plugin-compression";
import { VitePWA } from "vite-plugin-pwa";

// https://vitejs.dev/config/
export default defineConfig({
  build: {
    terserOptions: {
      compress: {
        drop_console: true,
        drop_debugger: true,
      },
    },
  },
  plugins: [
    viteCompression({
      verbose: true,
      algorithm: "gzip",
      threshold: 10240
    }),
    VitePWA({
      manifest: {
        name: "科技",
        short_name: "科技",
        display: "standalone",
        icons: [
          { src: "/logo*512.png", type: "image/png", sizes: "512x512" },
          { src: "/logo*256.png", type: "image/png", sizes: "256x256" },
          { src: "/logo*128.png", type: "image/png", sizes: "128x128" },
          { src: "/logo*64.png", type: "image/png", sizes: "64x64" },
        ],
        start_url: "/",
        background_color: "#F9F9F9",
        theme_color: "#3A3F51",
      },
      workbox: {
        skipWaiting: true,
        clientsClaim: true,
      },
    }),
    vue(),
  ],
});

```

After packaging...

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
  <script type="module" crossorigin src="/assets/index.d57a7ae8.js"></script>
  <link rel="modulepreload" href="/assets/vendor.170a6766.js">
  <link rel="stylesheet" href="/assets/index.ca835772.css">
<link rel="manifest" href="/manifest.webmanifest"></head>
  <body>
    <div id="app"></div>
    
  </body>
</html>

```

**Comment by userquin** [comment] 2021-06-08 10:05
@1018715564 by default, the service worker is configured to be auto with prompt for New content. You will need to add the logic to show the prompt using the virtual module or just add registerType with autoUpdate to the plugin  configuration.

**Comment by ArcherGu** [comment] 2021-06-11 06:54
Same problem, I had to manually include `registerSW.js` in the `index.html` after build to enable PWA.
```html
<script src="/registerSW.js"></script>
```

vite.config.ts:
```ts
// ...
        VitePWA({
            registerType: 'autoUpdate',
            manifest: {
                name: 'Foraging',
                short_name: 'Foraging',
                theme_color: '#8b5cf6',
                icons: [
                    {
                        src: '/pwa-250x250.png',
                        sizes: '250x250',
                        type: 'image/png',
                    },
                    {
                        src: '/pwa-300x300.png',
                        sizes: '300x300',
                        type: 'image/png',
                    },
                    {
                        src: '/pwa-300x300.png',
                        sizes: '300x300',
                        type: 'image/png',
                        purpose: 'maskable any',
                    },
                ],
            },
        }),
// ...
```

**Comment by ArcherGu** [comment] 2021-06-11 09:10
> Same problem, I had to manually include `registerSW.js` in the `index.html` after build to enable PWA.
> 
> ```
> <script src="/registerSW.js"></script>
> ```
> 
> vite.config.ts:
> 
> ```ts
> // ...
>         VitePWA({
>             registerType: 'autoUpdate',
>             manifest: {
>                 name: 'Foraging',
>                 short_name: 'Foraging',
>                 theme_color: '#8b5cf6',
>                 icons: [
>                     {
>                         src: '/pwa-250x250.png',
>                         sizes: '250x250',
>                         type: 'image/png',
>                     },
>                     {
>                         src: '/pwa-300x300.png',
>                         sizes: '300x300',
>                         type: 'image/png',
>                     },
>                     {
>                         src: '/pwa-300x300.png',
>                         sizes: '300x300',
>                         type: 'image/png',
>                         purpose: 'maskable any',
>                     },
>                 ],
>             },
>         }),
> // ...
> ```

I just solve my problem. At first, When I add: 
```ts
import { registerSW } from 'virtual:pwa-register';
registerSW();
```
Vite(rollup) can't resolve `workbox-window`.

So, I installed `workbox-window` manually and rebuild，everything's all right.

Question: Why do I need to install `workbox-window` manually, isn't it already included in `vite-plugin-pwa`?

**Comment by userquin** [comment] 2021-06-11 13:33
@ArcherGu see https://github.com/antfu/vite-plugin-pwa/issues/37

try to load virtual module using dynamic import, for example (you don't need to register on `index.html`):

`modules/pwa.ts` or `modules/pwa.js`
```ts
import { registerSW } from 'virtual:pwa-register'
registerSW()
```
then in your `main.ts` or `main.js`
```ts
if (import.meta.env.MODE === 'production') {
  import('@/modules/pwa')
}
```

**Comment by ArcherGu** [comment] 2021-06-12 06:29
@userquin Sorry, I just do like what you said, but still cant resolve `workbox-window` 😭

```bash
[vite]: Rollup failed to resolve import "workbox-window" from "../../../../../../@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "workbox-window" from "../../../../../../@vite-plugin-pwa/virtual:pwa-register".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by userquin** [comment] 2021-06-12 08:43
@ArcherGu is your repo public? If so, I can take a look...

**Comment by userquin** [comment] 2021-06-12 13:38
@ArcherGu

It seems we have some interference with the typescript, if we exclude the `workbox-window` dependency from the build, then the problem is that the pwa virtual module is generated as an esm module and since` workbox-window` is as a dev dependency, then it will be excluded from the bundle and fails on runtime. 

See my fork [here](https://github.com/userquin/foraging) ,with following changes build works, try to check if the logic is working:
- `pnpm up -D vite-plugin-pwa -L`: this will update to latest version `^0.8.1`
- `pnpm up -D vite -L`: will update to `^2.3.7`
- `pnpm up -D vue-tsc -L`: will update to `^0.1.7`
- `pnpm up -D typescript -L`: will update to `^4.3.2`
- added `workbox-window` to `dev dependencies`: `pnpm i -D workbox-window` => `^6.1.5`
- modified `onMounted` on `App.vue` with this:
```ts
if (import.meta.env.MODE === 'production' && typeof window !== 'undefined') {
  onMounted(async() => {
    const { registerSW } = await import('virtual:pwa-register');
    registerSW({ immediate: true });
  });
}
```
- updated `tsconfig.json` with:
```json
{
    "compilerOptions": {
        "baseUrl": ".",
        "module": "ESNext",
        "target": "ESNext",
        "lib": [ "ESNext", "DOM"],
        "strict": true,
        "esModuleInterop": true,
        "incremental": false,
        "skipLibCheck": true,
        "moduleResolution": "node",
        "jsx": "preserve",
        "sourceMap": true,
        "resolveJsonModule": true,
        "types": [
            "vite/client",
            "vite-plugin-pwa/client"
        ]
    },
    "include": [
        "src/**/*.ts",
        "src/**/*.d.ts",
        "src/**/*.tsx",
        "src/**/*.vue"
    ],
    "exclude": [
        "dist",
        "node_modules"
    ]
}
```

**Comment by userquin** [comment] 2021-06-14 11:40
@1018715564 @ArcherGu we close this issue, fill free to open a new one if the problem persists.

**Closed by userquin** 2021-06-14 11:40 UTC

**Comment by 1018715564** [comment] 2021-06-15 05:40
> @1018715564 @ArcherGu we close this issue, fill free to open a new one if the problem persists.

ok
