### ISSUE TITLE
Typescript IDE FAQ is not working

### ISSUE THREAD

**Issue by TheDutchCoder** [antfu/vite-plugin-pwa#149] opened 2021-11-03 16:58 UTC
I'm following this guide: https://vite-plugin-pwa.netlify.app/guide/faq.html#ide-errors-cannot-find-module-ts2307
In order to get rid of the TS errors in Vue SFC's, but it's not picking the types up when I add them to the config.

**Comment by antfu** [comment] 2021-11-03 17:02
We temporarily close this due to the lack of enough information. Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue. Thanks.

**Comment by TheDutchCoder** [comment] 2021-11-03 17:03
I think it's actually Volar not being able to deal with monorepos.
It works fine if I open the app as the root in VScode, but not if I open the root of the repo.

Sorry for the bother!

**Closed by antfu** 2021-11-03 17:02 UTC
