### ISSUE TITLE
is it possible to use vite-plugin-pwa with Nuxt3?

### ISSUE THREAD

**Issue by ctwhome** [antfu/vite-plugin-pwa#195] opened 2021-12-26 10:05 UTC
Hi, I have been trying to use it with Nuxt3 directly with the plugins system from Vite. it is my first try and so far it doesn't seem to be working: 

in nuxt.config.ts

```javascript
import { VitePWA } from 'vite-plugin-pwa'

  vite:{
    plugins: [
      VitePWA({
        includeAssets: ['favicon.svg', 'favicon.ico', 'robots.txt', 'apple-touch-icon.png'],
        manifest: {
          name: siteName,
          short_name: siteShortName,
          description: siteDescription,
          theme_color: '#FF0000',
          icons: [
            {src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png', },
            {src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png' },
            {src: 'pwa-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable',
            }
          ]
        }
      })
    ]
  }
```

I have put it in this wip repo: https://github.com/ctwhome/top-nuxt3

**Comment by userquin** [comment] 2021-12-26 13:17
@ctwhome I'll take a look:
- we need to disable nuxt pwa, it is generating its own `sw.js`, see the build `.output` folder (inside the `_nuxt` directory you can find the sw generated by this plugin on your repro)
- nuxt 3 is not yet released, and so not all modes are not yet ready: once released we'll take a look how we can add a module for this plugin

FYI: I clone your repo but I'm using `pnpm` instead `yarn`, you only need to run once installed via`pnpm install`: `pnpm i --shamefully-hoist`

**Comment by userquin** [comment] 2021-12-26 13:19
@ctwhome the `sw.js` is not created by `nuxt`, you have the `sw` on the public directory.

**Comment by userquin** [comment] 2021-12-26 18:26
@ctwhome I have it working,I just need to do some changes to support pages on offline (`about` on you repo), and I'll push to the main branch on my fork of your repro.

Anyway, this is a POC, we're waiting to the official `pwa module` on nuxt 3: I use `pnpm` as package manager.

I need to add a nuxt server middleware, use the inter plugin  communication like on `svetlekit` to make it work, take a look and new modules on root folder (`build-pwa.ts` and `pwa-configuration.ts`) and how I use them on `nuxt.config.ts`  and on `build` script on `package.json`, you will need to install `esno` as dev dependency. I also have included the `ReloadPrompt.vue` component and registering it on the default layout.

The `head` entry on `nuxt.config.ts` doesn't exist, it is `meta`, I have left a note on the configuration...

The app works and also with offline support.

I create a PR on your repo and so you can see the changes I applied to your codebase.

**Comment by userquin** [comment] 2021-12-26 18:33
@ctwhome the PR also includes offline support for `/about`...

closing this for now...

**Closed by userquin** 2021-12-26 18:33 UTC

**Comment by ChristopherJohnson25** [comment] 2022-05-18 16:53
Is this confirmed to have worked for Nuxt3? I only need` registerSW() `on nuxt3, any tips?

**Comment by userquin** [comment] 2022-05-18 16:56
@ChristopherJohnson25 check this entry and linked issues there on nuxt3 repo: https://github.com/ctwhome/top-nuxt3/issues/3

**Comment by re2005** [comment] 2022-11-09 11:57
Hi Guys, i'm following this issue and wondering if this plugin will work on `Nuxt3` 

For now I've tried and it doesn't properly works.

```js
Uncaught (in promise) non-precached-url: non-precached-url :: [{"url":"index.html"}]
```

Any help would be great.
Thanks!

**Comment by userquin** [comment] 2022-11-09 18:20
@re2005 try adding `navigationFallback: '/'` to  `workbox`  pwa plugin option.

I'm awaiting some nuxt changes to try to include also here (Vite PWA organization) an integration for Nuxt 3.

**Comment by re2005** [comment] 2022-12-14 17:12
Thanks @userquin I'll give it a try.

Other updates on this subject ?

Cheers

**Comment by userquin** [comment] 2022-12-14 17:20
@re2005 I'm working on it, we need some changes in Nuxt 3... I've it working on a private project with push notifications, the project will be also open source in a few weeks (I hope the first week on January we can release nuxt 3 pwa integration module)

**Comment by re2005** [comment] 2022-12-14 17:22
Ow, that's awesome, really good work. Good luck with it. Will keep an eye here.

Thanks!

**Comment by jamaluddinrumi** [comment] 2023-01-05 15:46
> @re2005 I'm working on it, we need some changes in Nuxt 3... I've it working on a private project with push notifications, the project will be also open source in a few weeks (I hope the first week on January we can release nuxt 3 pwa integration module)

really excited
can not waiting any longer
keep up for the nuxt 3 pwa integration!

**Comment by userquin** [comment] 2023-01-05 17:46
We've the application working with push notifications on alpha status, next week I'll start the integration, maybe adding also i18n pwa webmanifests support...

**Comment by Sjoerd82** [comment] 2023-01-08 18:08
Are we talking about [https://pwa.nuxtjs.org](https://pwa.nuxtjs.org)??

**Comment by userquin** [comment] 2023-01-08 18:30
> Are we talking about https://pwa.nuxtjs.org??

No, we're talking about `@vite-pwa/nuxt`, a new integration we'll start it next week, the logic is done, we only need to add the repo and publish it (I need to update my repo and then transfer it to vite org).

![imagen](https://user-images.githubusercontent.com/6311119/211212687-a3cb4781-6ac8-44a4-805c-5704f358aa14.png)

**Comment by Sjoerd82** [comment] 2023-01-08 18:59
Ah okay, exciting! --- At nuxt side, there's PWA mentioned at their roadmap for 2022, and at least two PWA modules that I know of, the one I mentioned and one by kevinmarrec. Is this going to be another separate option?

**Comment by userquin** [comment] 2023-01-08 19:34
Yes, `@vite-pwa/nuxt` will work only with Vite (webpack 4/5 will not work), about `kevinmarrec` integration you can use it with some limitations and about nuxt official pwa module I have no idea.

Check this tweet: https://twitter.com/userquin/status/1606967107325165570

**Comment by maoosi** [comment] 2023-01-19 06:02
Looking forward to it as well! Is there a way to start using the alpha version already?

**Comment by re2005** [comment] 2023-03-30 18:50
Hey @userquin really appreciate the nice work done on this plugin.

I wondering if is possible to use it on my `Nuxt v3 ` application, since the `@vite-pwa/nuxt` I can't manage to make it work.

Cheers

**Comment by userquin** [comment] 2023-03-30 19:17
@re2005  Ask on nuxt discird server, pwa room or send a new issue to pwa nuxt repo with some info and a small repro of possible
