### ISSUE TITLE
Migrating app from registerType `autoUpdate` to `prompt` results in broken state

### ISSUE THREAD

**Issue by danielberndt** [antfu/vite-plugin-pwa#228] opened 2022-02-12 22:18 UTC
Hi there 👋

The first versions of my app have been published using `registerType: "autoUpdate"`.
Now I'd like to offer a better UX and created an upgrade of my app to use `registerType: "prompt"`.

It seems though that all clients that have the old version of the app loaded, won't be able to load a new version.

Looking into it, the devtools tell me that the new version is present, but the app/service worker won't trigger a reload. Refreshing the browser window doesn't load the new version either.

![image](https://user-images.githubusercontent.com/856386/153730103-29e84e65-7fbb-4178-9a10-cf2e51f3bc09.png)

So it seems like users who have a `registerType: "autoUpdate"` version of the app loaded are stuck until they would manually remove the old service worker.

Is there something I can do make this type of migration possible?

**Comment by userquin** [comment] 2022-02-12 22:45
@danielberndt I think it is a edge case and I don't know how to solve it directly, I'll ask to someone on workbox but I don't promise you anything .

I'm testing it using `vue-router` example, I build the pwa with `autoUpdate`, open it on chrome, then I rebuild it using `prompt` strategy but the old sw is used intead the new one:

![imagen](https://user-images.githubusercontent.com/6311119/153730761-8c8bdae0-1319-4079-9aac-c9cf65460369.png)

but on the source code, both with the same code:

![imagen](https://user-images.githubusercontent.com/6311119/153730781-9f04666d-d18a-4c67-8ea4-7affec147c57.png)

I get the sw with the new strategy if I close all chrome windows and then reopen the app again: tested on non private browsing.

![imagen](https://user-images.githubusercontent.com/6311119/153730824-628f8490-dd8a-404f-9790-90f9aa4dafbf.png)

and once reopened:

![imagen](https://user-images.githubusercontent.com/6311119/153731128-ff8ed2cf-168d-4207-aba8-598d909b1a03.png)

**Comment by danielberndt** [comment] 2022-02-12 23:37
Thanks for the quick reply!

I've done some more experimenting. And I think I've somewhat succeeded by creating a custom `sw.js` containing code of registerTypes:

```js
[...]
self.skipWaiting();
clientsClaim();

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") self.skipWaiting();
});
```

Once all clients have loaded this version, I could remove the first two lines and the "prompt" strategy was working without these clients being stuck in the old version.

So maybe it's worth to add the `addEventListener` line even for the `autoUpade` type to ensure a migration is possible. 

Not really sure this is something that needs to happen in this library or in workbox though.

**Comment by userquin** [comment] 2022-02-13 00:32
@danielberndt The problem is that the sw is updated with the new strategy, but since we now have the prompt behavior the old app is still being used and so the new `ReloadPrompt` is not there.

I suggest you to not do this, if your users are under your control (not a public app), you can hint them to close the browser and reopen the app once you deploy the new version. 

Another approach: you can add an env property, for example `VITE_CONTROL_APP` and use `import.meta.env.VITE_CONTROL_APP` in the custom sw, if that variable is missing or `false` just use the `skipWaiting` otherwise use the `addEventListener`: you will need to deploy 2 versions, former with `false` to deploy the `ReloadPrompt` component and latter with `true`: this last deploy for example 1 or 2 days later, when you know all your clients have the former version.

**Comment by userquin** [comment] 2022-02-13 00:38
you can also use the `replace` plugin instead the `env` variable, for example using `__CONTROL_APP__`. check any example in this repo.

**Comment by danielberndt** [comment] 2022-02-13 11:57
Thanks for all your pointers! I will take a look at them :)

I guess one question to ask for this library (and/or for workbox?) is whether the use case of migrating from `autoUpdate` to `prompt` is considered an edge case which needs some deeper understanding of the internals to work yourself out of it, or whether this is something that should be supported "out of the box".

**Comment by userquin** [comment] 2022-03-09 13:52
@danielberndt closing this for now since it is not related how this plugin works, feel free open a new issue...

**Closed by userquin** 2022-03-09 13:52 UTC

**Comment by gilesbutler** [comment] 2024-05-30 04:58
Hey @danielberndt did you ever find a nice way of transitioning to `prompt` from `autoUpdate` in the end? Or @userquin have there been any other updates to this in the last two years? I saw in the [docs](https://vite-pwa-org.netlify.app/guide/auto-update.html#automatic-reload) there's still a huge danger warning against picking `autoUpdate`.

We have thousands of users on our app and we want to change from `autoUpdate` to `prompt` but we're too scared to go near it encase we lock out thousands of our core customers and have no way of telling them how to fix things. `autoUpdate`  is starting to cause lots of UX headaches as customers will be in the middle of something then every time we deploy their app gets refreshed without warning. It's costing us a lot of customers and something we'd love to fix but just not sure of the best path forward.

Appreciate any help or advice you can offer.

**Comment by danielberndt** [comment] 2024-05-30 07:35
> Hey @danielberndt did you ever find a nice way of transitioning to `prompt` from `autoUpdate` in the end?
No, I haven't. It was a side project with very few users anyway. So it was okay to tell users what to do if they got stuck.

**Comment by userquin** [comment] 2024-05-30 08:59
You can unregister current service worker and register a new one with the new prompt behavior. The old one will remove the current installed sw in all clients and then the app Will register a new one, remember to change the sw name, check https://vite-pwa-org.netlify.app/guide/unregister-service-worker.html#custom-selfdestroying-service-worker

**Comment by gilesbutler** [comment] 2024-05-31 06:36
Fantastic thanks @userquin, I wasn't aware of that so we'll look into it!

Thanks for replying too @danielberndt
