### ISSUE TITLE
Cannot access static resource

### ISSUE THREAD

**Issue by ansidev** [antfu/vite-plugin-pwa#73] opened 2021-06-06 18:55 UTC
Reproduce URL: https://vitesse.netlify.app/robots.txt

Expected: Raw content. A static resource can be plain text (like the above link or RSS URL), image, etc.
Actual: Vite page with `404 Not found` message.

**Comment by antfu** [comment] 2021-06-07 09:26
Transferred to vite-plugin-pwa. The problem is the request been hijacked by service worker.

**Comment by userquin** [comment] 2021-06-12 10:06
@antfu added PR to `vitesse` to solve missing sw manifest assets to work offline: https://github.com/antfu/vitesse/pull/139

**Closed** 2021-06-12 10:25 UTC
